#!/bin/sh
#
# Enable ESP-hosted WiFi and BT
#

start() {
    printf "(S97esp32_sdio) Enabling esp32..."
    modprobe esp32_sdio resetpin=107
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "(S97esp32_sdio) Disabling esp32..."
    modprobe -r esp32_sdio
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
