#!/bin/sh
#
# Reset/Re-bind USB driver
#

start() {
    printf "(S98resetusb) Re-binding USB driver... "
    echo 1c13000.usb > /sys/bus/platform/drivers/musb-sunxi/unbind
    echo 1c13000.usb > /sys/bus/platform/drivers/musb-sunxi/bind
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "(S98resetusb) Nothing to do. "
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
